image:
  repository: ghcr.io/centerionware/kube-nb-qd
  tag: latest
  pullPolicy: Always

namespace: kube-deploy

serviceAccount:
  name: kube-deploy-operator

resources:
  cpu: 100m
  memory: 128Mi

defaults:
  build:
    baseImage: node:20-alpine
    installCmd: "pnpm install"
    buildCmd: "pnpm build"
    registry:
      url: registry.registry.svc.cluster.local:5000
      repository: apps
      secretRef: ""
  run:
    command: "pnpm start"
    port: 3000

  service:
    annotations:
      netbird.io/expose: "true"
      netbird.io/groups: "media"
      netbird.io/policy: "media"
      netbird.io/sourceGroups: "Media-access"