apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-deploy-operator
  namespace: {{ .Values.namespace }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kube-deploy-operator

  template:
    metadata:
      labels:
        app: kube-deploy-operator

    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}

      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          resources:
            requests:
              cpu: {{ .Values.resources.cpu }}
              memory: {{ .Values.resources.memory }}
            limits:
              cpu: {{ .Values.resources.cpu }}
              memory: {{ .Values.resources.memory }}
            